//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvVillas_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_login
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_login()
        {
            this.tbl_peticion = new HashSet<tbl_peticion>();
        }
    
        public int ID_Login { get; set; }
        public string usr_login { get; set; }
        public string usr_password { get; set; }
        public string usr_tipoCedula { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_peticion> tbl_peticion { get; set; }
    }
}
